# Generated by Django 4.2.10 on 2024-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('image', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='サムネイル')),
                ('skill', models.CharField(max_length=100, verbose_name='スキル')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('created', models.DateField(verbose_name='作成日')),
                ('description', models.TextField(verbose_name='説明')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(max_length=1000, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=1000, verbose_name='仕事'),
        ),
    ]
