# Generated by Django 4.2.10 on 2024-11-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_education_experience_alter_profile_introduction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='cource',
            new_name='course',
        ),
    ]
