# Generated by Django 4.2.10 on 2024-11-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_software_technical'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qiita',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='qiita'),
        ),
    ]
